name: goal_driven_segm
channels:
  - conda-forge
dependencies:
  - python=3.6.10
  - pip=20.0.2
  - numpy=1.18.1
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - matplotlib=3.1.3
  - tqdm=4.42.1

